pool:
  vmImage: ubuntu-latest
  
resources:
  pipelines:
  - pipeline: drop
    source: build
    trigger:
      branches:
        include:
        - master

variables:
  appName: 'cf-portal-api'
  location: 'westeurope'
  locationUS: 'westus'
  azureSubscription: 'CFPortal'


stages:
- template: ./deploy-stages.yaml
  parameters:
    connectionName: $(azureSubscription)
    resourceGroup: cfportal-qa
    env: qa
    appName: $(appName)  

- ${{ if eq(variables['Build.Reason'], 'Manual') }}:
  - template: ./deploy-stages.yaml
    parameters:
      connectionName: $(azureSubscription)
      resourceGroup: cfportal-prod
      env: prod
      appName: $(appName)

