trigger: none
pr: none


  
resources:
  pipelines:
  - pipeline: api
    source: api-build
    trigger:
      branches:
        include:
        - master
        - develop
        - release*

pool:
  vmImage: ubuntu-latest
  


variables:
  appName: 'cf-portal-api'
  azureSubscription: 'Pipline2'


stages:
#-stage: qa
#  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))  
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
  - template: ./api-deploy-stages.yaml
    parameters:
      connectionName: $(azureSubscription)
      env: qa
      appName: $(appName)  
- ${{ if eq(variables['Build.Reason'], 'Manual') }}:
  - template: ./api-deploy-stages.yaml
    parameters:
      connectionName: $(azureSubscription)
      env: prod
      appName: $(appName)

