trigger:
  batch: false
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest
  


variables:
  appName: 'cf-portal-api'
  azureSubscription: 'Pipline2'


stages:
- template: ./deploy-stages.yaml
  parameters:
    connectionName: $(azureSubscription)
    resourceGroup: eben-api
    env: qa
    appName: $(appName)  

- ${{ if eq(variables['Build.Reason'], 'Manual') }}:
  - template: ./deploy-stages.yaml
    parameters:
      connectionName: $(azureSubscription)
      resourceGroup: cfportal-prod
      env: prod
      appName: $(appName)

