trigger:
  batch: false
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest
  


variables:
  appName: 'cf-portal-api'
  location: 'westeurope'
  locationUS: 'westus'
  azureSubscription: 'Pipline2'


stages:
- template: ./deploy-stages.yaml
  parameters:
    connectionName: $(azureSubscription)
    resourceGroup: cfportal-qa
    env: qa
    appName: $(appName)  

- ${{ if eq(variables['Build.Reason'], 'Manual') }}:
  - template: ./deploy-stages.yaml
    parameters:
      connectionName: $(azureSubscription)
      resourceGroup: cfportal-prod
      env: prod
      appName: $(appName)

