parameters:
  - name: connectionName
    type: string
  - name: env
    type: string
    values:
    - qa
    - qanew
    - temp
    - prod
  - name: appName
    type: string

stages:
- stage: ${{ format('{0}_Infrastructure', parameters.env) }}
  variables:
  - template: ${{ format('{0}-vars.yaml', parameters.env) }}
  # - group: ${{ format('{0}-vars', parameters.env) }}
  jobs:
  - deployment: Infrastructure
    displayName: 'Deploy infrastructure'
    workspace:
      clean: all 
    environment: ${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Deploy Bicep template'
            inputs:
              azureSubscription: ${{ parameters.connectionName }}
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                $outputs = az deployment group create `
                --resource-group ${{ ResourceGroup }} `
                --template-file '$(Build.SourcesDirectory)/provisioning/infrastructure/main.bicep' `
                --parameters $(BicepParametersFile) `
                --query properties.outputs | ConvertFrom-Json
