name: 1.0.$(Year:yy)$(DayOfYear)$(Rev:.r)

trigger:
  batch: false
  branches:
    include:
      - master
stages: 
- stage: Build_and_Test
  displayName: 'Build and Test'
  jobs:
  - job:
    pool:  
      vmimage: 'windows-2019'
    displayName: 'Build and Test'
    steps: 
            - task: DotNetCoreCLI@2
              displayName: 'dotnet restore'
              inputs:
                command: 'restore'
                projects: '**/Web.csproj'
                feedsToUse: 'select'

            - task: DotNetCoreCLI@2
              displayName: 'dotnet build'
              inputs:
                command: build
                projects: '**/*.sln'
                arguments:  ' --no-restore --configuration Release'

            - task: DotNetCoreCLI@2
              displayName: 'publish'
              inputs:
                command: 'publish'
                publishWebProjects: true
                arguments: ' --output $(Build.ArtifactStagingDirectory) --configuration Release'
                zipAfterPublish: True

            # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
            - task: PublishPipelineArtifact@1
              displayName: 'staging dir $(Build.ArtifactStagingDirectory)'
              inputs:
                targetPath: '$(Build.ArtifactStagingDirectory)' 
                artifactName: 'ebsSiteTester'
                 
- stage: QA 
  displayName: 'QA'
  condition: succeeded() # and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))  
  jobs:
  - deployment: 
    pool:  
      vmimage: 'windows-2019'
    displayName: 'QA'
    environment: 'QA'
    strategy:
     runOnce:
        deploy:
           steps:             
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'ebsSiteTester'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: ExtractFiles@1
              displayName: 'extracting dir $(Build.ArtifactStagingDirectory)'
              inputs:
                archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/**/*.zip'
                destinationFolder: '$(System.DefaultWorkingDirectory)/source'
                cleanDestinationFolder: true
                overwriteExistingFiles: false
 
            # - task: FileTransform@1
            #   inputs:
            #     folderPath: '$(System.DefaultWorkingDirectory)/source/'
            #     fileType: 'json'
            #     targetFiles: 'appsettings.json'
                
            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'Pipline2'
                appType: 'webApp'
                appName: 'cf-portal-api-app-qa'
                package: '$(System.DefaultWorkingDirectory)/source/'
                deploymentMethod: 'auto'

